export enum ActivityTypeEnum {
  BOOK_CREATED = 'BOOK_CREATED',
  BOOK_UPDATED = 'BOOK_UPDATED',
  BOOK_DELETED = 'BOOK_DELETED',
  BORROWING_CREATED = 'BORROWING_CREATED',
  BORROWING_RETURNED = 'BORROWING_RETURNED',
  RESERVATION_CREATED = 'RESERVATION_CREATED',
  RESERVATION_CANCELLED = 'RESERVATION_CANCELLED',
  USER_ROLE_UPDATED = 'USER_ROLE_UPDATED',
  USER_WHITELIST_UPDATED = 'USER_WHITELIST_UPDATED',
}
